sampdata <- read.table("household_power_consumption.txt",header=TRUE,sep=';',nrows=5)
classes <- sapply(sampdata, class)
alldata <- read.table("household_power_consumption.txt",header=TRUE,sep=';',na.strings='?',colClasses=classes)
febdata <- subset(alldata, alldata$Date == "1/2/2007" | alldata$Date == "2/2/2007")
rm(alldata)
i <- sapply(febdata, is.factor)
febdata[i] <- lapply(febdata[i], as.character)
str(febdata)
febdattim <- paste(febdata$Date,febdata$Time)
febdate <- strptime(febdattim,format="%d/%m/%Y %H:%M:%S")

par(mfrow=c(2,2))
par(cex=0.6,mar=c(4,4,2,2))
plot(febdate,febdata$Global_active_power,'l',main="",xlab='',ylab="Global Active Power (kW)")
plot(febdate,febdata$Voltage,'l',main="",xlab='datetime',ylab="Voltage")
plot(febdate,febdata$Sub_metering_1,'l',main="",xlab='',ylab="Energy sub-metering (kW)")
lines(febdate,febdata$Sub_metering_2,'l',col='red')
lines(febdate,febdata$Sub_metering_3,'l',col='blue')
names <- c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
legend("topright", names, col=c("black","red","blue"),lty=1,bty='n',cex=0.8)
plot(febdate,febdata$Global_reactive_power,'l',main="",xlab='datetime',ylab="Global Reactive Power (kW)")

dev.copy(png,file="plot4.png")
dev.off()
