sampdata <- read.table("household_power_consumption.txt",header=TRUE,sep=';',nrows=5)
classes <- sapply(sampdata, class)
alldata <- read.table("household_power_consumption.txt",header=TRUE,sep=';',na.strings='?',colClasses=classes)
febdata <- subset(alldata, alldata$Date == "1/2/2007" | alldata$Date == "2/2/2007")
rm(alldata)
i <- sapply(febdata, is.factor)
febdata[i] <- lapply(febdata[i], as.character)
str(febdata)
febdattim <- paste(febdata$Date,febdata$Time)
febdate <- strptime(febdattim,format="%d/%m/%Y %H:%M:%S")

par(cex=0.8,mar=c(5,5,4,3))
plot(febdate,febdata$Sub_metering_1,'l',main="",xlab='',ylab="Energy sub-metering (kW)",cex=0.8)
lines(febdate,febdata$Sub_metering_2,'l',col='red')
lines(febdate,febdata$Sub_metering_3,'l',col='blue')
names <- c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
legend("topright", names, col=c("black","red","blue"),lty=1,cex=0.8)
dev.copy(png,file="plot3.png")
dev.off()
